paths:
  input_folder: "/Users/nunny/Desktop/Shipping-File-Automation/mainfolder/input"
  output_folder: "/Users/nunny/Desktop/Shipping-File-Automation/mainfolder/output"
  mapping_file: "/Users/nunny/Desktop/Shipping-File-Automation/mainfolder/AccCode_Mapping.csv"
